version = 1

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "8"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["vue"]
  environment = ["nodejs"]

[[analyzers]]
name = "shell"